config/routes.rb
SampleApp::Application.routes.draw do
  
  resources :users do
    member do
      get :member
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :groups do
    member do
      get :leader
    end
  end
  resources :leader_member_relationships, only: [:create, :destroy]

  resource :calendar, only: [:show], controller: :calendar
  
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/newgroup', to: 'groups#new',       via: 'get'
  

end

app/models/group.rb
class Group < ActiveRecord::Base
	belongs_to :user
	has_many :leader_member_relationships, foreign_key: "leader_id", dependent: :destroy
	has_many :members, through: :relationships, source: :leader

	default_scope -> { order('created_at DESC') }
	validates :name, presence: true, uniqueness: true
	validates :user_id, presence: true
	validates :description, presence: true

	 def leader?(user)
    leader_member_relationships.find_by(member_id: user.id)
  end

  def add!(user)
    leader_member_relationships.create!(member_id: user.id)
  end

  def remove!(user)
    leader_member_relationships.find_by(leader_id: user.id).destroy
  end
end

app/models/group_user_relationship.rb
class GroupUserRelationship < ActiveRecord::Base
	belongs_to :member, class_name: "User"
 	belongs_to :leader, class_name: "Group"
 	validates :member_id, presence: true
    validates :leader_id, presence: true
end

app/models/leader_member_relationship.rb
class LeaderMemberRelationship < ActiveRecord::Base
	belongs_to :member, class_name: "User"
 	belongs_to :leader, class_name: "Group"
 	validates :member_id, presence: true
    validates :leader_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :groups, dependent: :destroy
  has_many :leader_member_relationships, foreign_key: "member_id", dependent: :destroy
  has_many :leaders, through: :relationships, source: :member


	before_save { self.email = email.downcase }
	before_create :create_remember_token

	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  	validates :email, presence: true, 
  			          format: { with: VALID_EMAIL_REGEX }, 
  					  uniqueness: { case_sensitive: false }
  	has_secure_password
  	validates :password, length: { minimum: 6 }
  	def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

   def member?(group)
    leader_member_relationships.find_by(leader_id: group.id)
  end

  def join!(group)
    leader_member_relationships.create!(leader_id: group.id)
  end

  def leave!(group)
    leader_member_relationships.find_by(leader_id: group.id).destroy
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
   include SessionsHelper
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def show
  	 @date = params[:date] ? Date.parse(params[:date]) : Date.today
  	 #@events_by_date = Event.group_by(&:date)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
  	@group = Group.new
  end
  def create
    @group = Group.new(group_params)
    if signed_in?
    	@group.user_id = current_user.id
	else
		render 'new'
	end

    if @group.save
      flash[:success] = "Your group has been created!"
      redirect_to @group
    else
      render 'new'
    end
  end

  def index
    @groups = Group.paginate(page: params[:page])
  end

	def show
    @group = Group.find(params[:id])
  end

  private

    def group_params
      params.require(:group).permit(:name, :description)
    end


    

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

	def show
    @user = User.find(params[:id])
    @groups = @user.groups.paginate(page: params[:page])
  end

  def new
  	@user = User.new
  end
  def create
    @user = User.new(user_params) 
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  def edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
     flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end
  

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Joshua's Big Day"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  
   def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

   def current_user?(user)
    user == current_user
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/calendar/show.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <div class="well controls">
      <%= link_to calendar_path(date: @date - 1.month), class: "btn btn-default" do %>
        <i class="glyphicon glyphicon-backward"></i>
      <% end %>
      <%= "#{@date.strftime("%B")} #{@date.year}" %>
      <%= link_to calendar_path(date: @date + 1.month), class: "btn btn-default" do %>
        <i class="glyphicon glyphicon-forward"></i>
      <% end %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= calendar @date do |date| %>
      <%= date.day %>
       <% if @events_by_date[date] %>
    		<ul>
      			<% @events_by_date[date].each do |event| %>
        			<li><%= link_to event.name, event %></li>
      	<% end %>
    </ul>
  <% end %>  
    
    <% end %>
  </div>
</div>

app/views/groups/_error_messages.html.erb
<% if @group.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@group.errors.count, "error") %>.
    </div>
    <ul>
    <% @group.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/groups/_group.html.erb
<li>
	<span class="title"><%= link_to group.name, group %></span>
  <span class="content"><%= group.description %></span>
  <span class="timestamp">
    Created <%= time_ago_in_words(group.created_at) %> ago.
  </span>
  
</li>

app/views/groups/index.html.erb
<% provide(:title, 'All groups') %>
<h1>All groups</h1>

<%= will_paginate %>

<ul class="groups">
  <%= render @groups %>
</ul>

<%= will_paginate %>

app/views/groups/new.html.erb
<% provide(:title, 'New Group') %>
<h1>New Group</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@group) do |f| %>
    <%= render 'error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :description %>
      <%= f.text_field :description %>

      
      <%= f.submit "Create my group", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<% provide(:title, @group.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= @group.name %>
      </h1>
      <p>
        <%= @group.description %>
      </p>
    </section>
<section>
  <% render 'shared/join_form' if signed_in? %> 
</section>

  </aside>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer" style="padding:10px">
  <small>
    Joshua's Big Day
    <br>
    Work in Progress
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://img0.liveinternet.ru/images/attach/c/5/3970/3970473_sprite198.swf">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Joshua's Big Day", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Groups", groups_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_join.html.erb
<%= form_for(current_user.leader_member_relationships.build(leader_id: @group.id)) do |f| %>
  <div><%= f.hidden_field :member_id %></div>
  <%= f.submit "Join", class: "btn btn-small btn-primary" %>
<% end %>

app/views/shared/_join_form.html.erb
  <div id="follow_form">
  <% if current_user.member?(@group) %>
    <%= render 'shared/leave' %>
  <% else %>
    <%= render 'shared/join' %>
  <% end %>
  </div>

app/views/shared/_leave.html.erb
<%= form_for(current_user.leader_member_relationships.find_by(member_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Leave", class: "btn btn-small" %>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us')%>
    <h1>About Us</h1>
    <p>
      It's a work in progress.
    </p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact us <a href="http://www.omfgdogs.com/">here.</a>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help')%>
    <h1>Help</h1>
    <p>
      This is the Help page. It'll be more extensive in the future.
    </p>

app/views/static_pages/home.html.erb
<div class="text-center">
<h1>MyDay App</h1>
<h2>
  This is the home page for the MyDay App.
</h2>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>

<div>
 <%= link_to "Create Group", newgroup_path, class: "btn btn-med btn-primary" %>
</div>

<div class="span8">
    <% if @user.groups.any? %>
      <h3>Groups (<%= @user.groups.count %>)</h3>
      <ol class="groups">
        <%= render @groups %>
      </ol>
      <%= will_paginate @groups %>
    <% end %>
  </div>


<br><br><br>
<div id="calendar">
  <%= calendar_for(@users) do |t| %>
  <%= t.head('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun') %>
  <%= t.day do |day, users| %>
    <%= day.day %>
    <% users.each do |user| %>
      <%= h(user.name) %>
    <% end %>
  <% end %>
<% end %>


</div>